#pragma once

#include "XRNM_EVENT_DATA_RECEIVED.h"
#include "XRNM_EVENT_RECEIVE_CHANNEL_CREATED.h"
#include "XRNM_EVENT_RECEIVE_CHANNEL_TERMINATED.h"
#include "XRNM_EVENT_SEND_CHANNEL_TERMINATED.h"
#include "XRNM_EVENT_SEND_BUFFER_RETURNED.h"
#include "XRNM_EVENT_SEND_BUFFER_RECEIPT.h"
#include "XRNM_EVENT_LINK_STATUS.h"
#include "XRNM_EVENT_ENDPOINT_INCOMING_LINK_REQUEST.h"
#include "XRNM_EVENT_ALERT.h"
#include "XRNM_EVENT_ENDPOINT_ADDRESSES_CHANGED.h"

struct XRNM_EVENT
{
	int32_t mCbSize;
	int32_t mEventType;
};